# Generated by Django 4.2.15 on 2024-09-02 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sdi_geocoder.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdi_geocoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcsv',
            name='data_scheme',
            field=models.JSONField(default=sdi_geocoder.models.data_scheme, max_length=1024, verbose_name='Datenschema'),
        ),
        migrations.CreateModel(
            name='OgcApiFeaturesCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('geom_type', models.CharField(max_length=1024, verbose_name='Geometrietyp')),
                ('data_scheme', models.JSONField(default=sdi_geocoder.models.data_scheme, verbose_name='Datenmodell')),
                ('owned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OgcApiFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('base_uri', models.CharField(max_length=1024, verbose_name='Basis-URL')),
                ('owned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
