# Generated by Django 4.2.15 on 2024-09-02 05:43

from django.db import migrations, models
import django.db.models.deletion
import sdi_geocoder.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0002_rawcsv_data_scheme_ogcapifeaturescollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogcapifeaturescollection',
            name='ogc_api_features',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sdi_geocoder.ogcapifeatures', verbose_name='OGC API Features'),
        ),
        migrations.AlterField(
            model_name='ogcapifeaturescollection',
            name='data_scheme',
            field=models.JSONField(default=sdi_geocoder.models.data_scheme, editable=False, verbose_name='Datenmodell'),
        ),
    ]
