# Generated by Django 4.2.15 on 2024-09-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0003_ogcapifeaturescollection_ogc_api_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcsv',
            name='data_scheme',
            field=models.JSONField(max_length=1024, null=True, verbose_name='Datenschema'),
        ),
    ]
