# Generated by Django 4.2.15 on 2024-09-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0004_alter_rawcsv_data_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogcapifeaturescollection',
            name='data_scheme',
            field=models.JSONField(editable=False, null=True, verbose_name='Datenmodell'),
        ),
    ]
