# Generated by Django 4.2.15 on 2024-09-02 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdi_geocoder', '0005_alter_ogcapifeaturescollection_data_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1024, verbose_name='Titel')),
                ('ogc_api_feature_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdi_geocoder.ogcapifeaturescollection', verbose_name='OGC API Feature Collection')),
                ('owned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('raw_csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdi_geocoder.rawcsv', verbose_name='CSV-Datei')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoCodingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('line_number', models.IntegerField(editable=False, null=True, verbose_name='Zeilennummer')),
                ('result', models.BooleanField(editable=False, null=True, verbose_name='Ergebnis')),
                ('error_message', models.JSONField(editable=False, null=True, verbose_name='Fehlermeldung')),
                ('geometry_object', models.JSONField(editable=False, null=True, verbose_name='Geometrieobjekt')),
                ('geo_coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdi_geocoder.geocoding', verbose_name='Geocoding')),
                ('owned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
