# Generated by Django 4.2.15 on 2024-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0007_remove_ogcapifeatures_name_ogcapifeatures_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogcapifeatures',
            name='base_uri',
            field=models.URLField(verbose_name='Basis-URL'),
        ),
    ]
