# Generated by Django 4.2.15 on 2024-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0008_alter_ogcapifeatures_base_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogcapifeatures',
            name='base_uri',
            field=models.URLField(unique=True, verbose_name='Basis-URL'),
        ),
    ]
