# Generated by Django 4.2.15 on 2024-09-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0009_alter_ogcapifeatures_base_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocoding',
            name='feature_collection',
            field=models.JSONField(editable=False, null=True, verbose_name='Geometrieobjekte'),
        ),
    ]
