# Generated by Django 4.2.15 on 2024-09-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0010_geocoding_feature_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodingresult',
            name='get_url',
            field=models.URLField(null=True, verbose_name='GET-Url'),
        ),
    ]
