# Generated by Django 4.2.15 on 2024-09-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0011_geocodingresult_get_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocodingresult',
            options={'ordering': ['line_number']},
        ),
        migrations.RemoveField(
            model_name='ogcapifeaturescollection',
            name='data_scheme',
        ),
        migrations.AddField(
            model_name='ogcapifeaturescollection',
            name='data_example',
            field=models.JSONField(editable=False, null=True, verbose_name='Beispieldatensatz'),
        ),
    ]
