# Generated by Django 4.2.15 on 2024-09-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0012_alter_geocodingresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcsv',
            name='rows',
            field=models.IntegerField(null=True, verbose_name='Anzahl der Datenzeilen'),
        ),
    ]
