# Generated by Django 4.2.16 on 2024-09-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_geocoder', '0013_rawcsv_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocoding',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich verfügbar'),
        ),
    ]
